<pre class='metadata'>
Title: Compute Pressure API
Shortname: compute-pressure
Level: 1
Status: CG-DRAFT
Group: WICG
Repository: WICG/compute-pressure
URL: http://example.com/url-this-spec-will-live-at
Editor: Olivier Yiptong, Google Inc. https://google.com, oyiptong@google.com
Editor: Victor Costan, Google Inc. https://google.com, costan@google.com
!Tests: <a href=https://github.com/w3c/web-platform-tests/tree/master/compute-pressure>web-platform-tests compute-pressure/</a> (<a href=https://github.com/w3c/web-platform-tests/labels/compute-pressure>ongoing work</a>)
Abstract: A short description of your spec, one or two sentences.
</pre>

Introduction {#intro}
=====================

See https://github.com/tabatkins/bikeshed to get started.
